In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import os
os.chdir('d:/Users/mokky/Documents/GitHub/nus-iss/PRS-PM-ISY5002-GROUP5/SystemCode')
print(os.getcwd())

d:\Users\mokky\Documents\GitHub\nus-iss\PRS-PM-ISY5002-GROUP5\SystemCode


In [3]:
import pandas as pd
import numpy as np
import constants_uc3 

In [4]:
file_path = './Data Exploration/data/uc3/BillEstimate.csv'
df = pd.read_csv(file_path, parse_dates=['ACTUAL_ADMISSION_DTE', 'ADM_DATE', 'DOB'])
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 62517 entries, 0 to 62516
Data columns (total 49 columns):
 #   Column                        Non-Null Count  Dtype         
---  ------                        --------------  -----         
 0   ACTUAL_CASE_NUMBER            62517 non-null  int64         
 1   ACTUAL_TREATMENT_CATEGORY     62517 non-null  object        
 2   ACTUAL_PATIENT_NUMBER         62517 non-null  int64         
 3   ACTUAL_PRIMARY_DIAGNOSIS_SID  62517 non-null  int64         
 4   ACTUAL_CASE_INSTITUTION       62517 non-null  object        
 5   ACTUAL_ADMISSION_DTE          62517 non-null  datetime64[ns]
 6   ACTUAL_LOS                    62517 non-null  int64         
 7   ACTUAL_ICU_HDU_LOS            49 non-null     float64       
 8   ACTUAL_SURGICAL_CODE_1        43688 non-null  object        
 9   ACTUAL_SURGICAL_CODE_2        16939 non-null  object        
 10  ACTUAL_SURGICAL_CODE_3        3422 non-null   object        
 11  ACTUAL_DIAGNOSIS_CODE       

In [5]:
print(df.select_dtypes(include=['object']).nunique())

ACTUAL_TREATMENT_CATEGORY      51
ACTUAL_CASE_INSTITUTION         4
ACTUAL_SURGICAL_CODE_1       1343
ACTUAL_SURGICAL_CODE_2        849
ACTUAL_SURGICAL_CODE_3        496
ACTUAL_DIAGNOSIS_CODE        3770
INST                            8
ETBS_ICU_HDU_LOS               12
ETBS_MOVE_TYPE                 11
ETBS_TOSP_1                  1441
ETBS_TOSP_2                   648
ETBS_TOSP_3                   227
ETBS_ICD10_1                 2342
ETBS_ICD10_2                  267
ETBS_ICD10_3                   37
CASE_TYPE                       1
ADMISSION_TYPE                  8
TREATMENT_CATEGORY             55
REFERRAL_TYPE                  33
DEPT_OU                        93
ADMITTING_SMC_NUMBER         1102
ATTENDING_SMC_NUMBER         1124
REFERRAL_SMC_NUMBER           935
ADM_CLASS_DISC                 12
GENDER                          3
MARITAL_STATUS                  7
RELIGION                       17
NATIONALITY                   198
RESID_CTY                      88
OCCUPATION    

In [6]:
print('ACTUAL_CASE_INSTITUTION vs INST: ',
      df.groupby(by=['ACTUAL_CASE_INSTITUTION'])['INST'].nunique().max())
print(df.groupby(by=['ACTUAL_CASE_INSTITUTION'])['INST'].unique())
print(df['ACTUAL_CASE_INSTITUTION'].unique())
print(df['INST'].unique())

ACTUAL_CASE_INSTITUTION vs INST:  2
ACTUAL_CASE_INSTITUTION
ghl    [ghl, GHL]
meh    [meh, MEH]
peh    [peh, PEH]
pnh    [pnh, PNH]
Name: INST, dtype: object
['ghl' 'meh' 'pnh' 'peh']
['ghl' 'meh' 'pnh' 'peh' 'PNH' 'GHL' 'MEH' 'PEH']


In [118]:
print('ACTUAL_LOS vs ETBS_ICU_HDU_LOS: ',
      df.groupby(by=['ACTUAL_LOS'])['ETBS_ICU_HDU_LOS'].nunique().max())

ACTUAL_LOS vs ETBS_ICU_HDU_LOS:  11


In [127]:
print(df['ETBS_ICU_HDU_LOS'].unique())
print(df['ETBS_ICU_HDU_LOS'].fillna(0).replace('MISSING', 0).astype(np.number).unique())

['MISSING' nan '1' '2' '3' '4' 1.0 5.0 3.0 2.0 4.0 7.0 9.0]
[0. 1. 2. 3. 4. 5. 7. 9.]


In [8]:
for col in df.select_dtypes(include=['object']).columns:
    print(col)
    print(df[col].unique())

ACTUAL_TREATMENT_CATEGORY
['endo' 'dw2b' 'dc' 'dw1b' 'sgl' 'dc1' 'ni2b' '4bd' '2bd' 'a1' 'vip2'
 'nursp' 'hdu' 'sgln' 'ni1' 'dc2b' 'tusgl' 'exe' 'icu' 'sup' 'vip' 'ryl'
 'argon' 'dlx' 'eye' 'yag' '2bdw14' 'sgls' 'dc4b' 'hbc' 'ni3' 'dc1b'
 'ryl1' 'edlx' 'dal' 'vip3' 'glen' 'tu2bd' 'iod' 'daf' 'sglw14' 'orc'
 'ni2a' '4bdw14' 'si35' 'tangln' 'dem' 'nur1' 'rylll' 'ryl2' 'ryll']
ACTUAL_CASE_INSTITUTION
['ghl' 'meh' 'pnh' 'peh']
ACTUAL_SURGICAL_CODE_1
['sf710c' 'sf701i' 'sf704c' ... 'sf817m' 'sf713m' 'sd736a']
ACTUAL_SURGICAL_CODE_2
[nan 'sf701i' 'sk759e' 'sf834a' 'sl714e' 'sm724n' 'si843u' 'sk703s'
 'sf838a' 'sf700i' 'sc719t' 'sf836a' 'sk728n' 'sf702c' 'sg709b' 'sf849a'
 'sg700u' 'sa706b' 'sb707k' 'si725u' 'sh802v' 'se700l' 'sm700n' 'sk705s'
 'sd708h' 'sf707t' 'sd717v' 'NA_VALUE' 'si705c' 'sm711s' 'sm714n' 'sm839m'
 'sd811h' 'sg716b' 'sm700i' 'si704c' 'sb806j' 'sc704b' 'sm707s' 'sf801a'
 'si816u' 'sf704c' 'sj701t' 'sm713n' 'sa853s' 'sa840s' 'sf705c' 'sc715t'
 'sb700s' 'sb820t' 'sa716s' 'si7

In [9]:
not_listed = []
for value in df['ACTUAL_TREATMENT_CATEGORY'].str.upper().unique():
    if value not in constants_uc3.TREATMENT_TYPES:
        not_listed.append(value)
print(not_listed)

[]


In [10]:
not_listed = []
for value in df['ACTUAL_CASE_INSTITUTION'].str.upper().unique():
    if value not in constants_uc3.INSTITUTION_TYPES:
        not_listed.append(value)
print(not_listed)

[]


In [55]:
not_listed = []
for value in df['ACTUAL_SURGICAL_CODE_1'].str.upper().unique():
    if value not in constants_uc3.TOSP_CODES:
        not_listed.append(value)
print(not_listed)

[nan, 'NA_VALUE']


In [57]:
not_listed = []
for value in df['ACTUAL_SURGICAL_CODE_2'].str.upper().unique():
    if value not in constants_uc3.TOSP_CODES:
        not_listed.append(value)
print(not_listed)

[nan, 'NA_VALUE']


In [58]:
not_listed = []
for value in df['ACTUAL_DIAGNOSIS_CODE'].str.upper().unique():
    if value not in constants_uc3.ICD_CODES:
        not_listed.append(value)
print(not_listed)

[nan]


In [60]:
not_listed = []
for value in df['ACTUAL_SURGICAL_CODE_3'].str.upper().unique():
    if value not in constants_uc3.TOSP_CODES:
        not_listed.append(value)
print(not_listed)

[nan, 'NA_VALUE']


In [15]:
not_listed = []
for value in df['INST'].str.upper().unique():
    if value not in constants_uc3.INSTITUTION_TYPES:
        not_listed.append(value)
print(not_listed)

[]


In [16]:
not_listed = []
for value in df['ETBS_MOVE_TYPE'].str.upper().unique():
    if value not in constants_uc3.ADMISSION_TYPES:
        not_listed.append(value)
print(not_listed)

[]


In [62]:
not_listed = []
for value in df['ETBS_TOSP_1'].str.upper().unique():
    if value not in constants_uc3.TOSP_CODES:
        not_listed.append(value)
print(not_listed)

[nan, ' ']


In [69]:
not_listed = []
for value in df['ETBS_TOSP_2'].str.upper().unique():
    if value not in constants_uc3.TOSP_CODES:
        not_listed.append(value)
print(not_listed)

[nan, ' ']


In [66]:
not_listed = []
for value in df['ETBS_TOSP_3'].str.upper().unique():
    if value not in constants_uc3.TOSP_CODES:
        not_listed.append(value)
print(not_listed)

[nan, ' ']


In [68]:
not_listed = []
for value in df['ETBS_ICD10_1'].str.upper().unique():
    if value not in constants_uc3.ICD_CODES:
        not_listed.append(value)
print(not_listed)

[nan]


In [71]:
not_listed = []
for value in df['ETBS_ICD10_2'].str.upper().unique():
    if value not in constants_uc3.ICD_CODES:
        not_listed.append(value)
print(not_listed)

[nan]


In [72]:
not_listed = []
for value in df['ETBS_ICD10_3'].str.upper().unique():
    if value not in constants_uc3.ICD_CODES:
        not_listed.append(value)
print(not_listed)

[nan]


In [23]:
not_listed = []
for value in df['ADMISSION_TYPE'].str.upper().unique():
    if value not in constants_uc3.ADMISSION_TYPES:
        not_listed.append(value)
print(not_listed)

[nan]


In [74]:
not_listed = []
for value in df['TREATMENT_CATEGORY'].str.upper().unique():
    if value not in constants_uc3.TREATMENT_TYPES:
        not_listed.append(value)
print(not_listed)

[nan]


In [101]:
not_listed = []
for value in df['DEPT_OU'].str.upper().unique():
    if value not in constants_uc3.DEPT_OUS:
        not_listed.append(value)
print(not_listed)

[nan]


In [76]:
not_listed = []
for value in df['ADMITTING_SMC_NUMBER'].str.upper().unique():
    if value not in constants_uc3.DOCTOR_CODES:
        not_listed.append(value)
print(not_listed)

[nan]


In [78]:
not_listed = []
for value in df['ATTENDING_SMC_NUMBER'].str.upper().unique():
    if value not in constants_uc3.DOCTOR_CODES:
        not_listed.append(value)
print(not_listed)

[nan]


In [80]:
not_listed = []
for value in df['REFERRAL_SMC_NUMBER'].str.upper().unique():
    if value not in constants_uc3.DOCTOR_CODES:
        not_listed.append(value)
print(not_listed)

[nan]


In [104]:
not_listed = []
for value in df['ADM_CLASS_DISC'].str.upper().unique():
    if value not in constants_uc3.ADM_CLASSES:
        not_listed.append(value)
print(not_listed)

[nan]


In [32]:
not_listed = []
for value in df['GENDER'].str.upper().unique():
    if value not in constants_uc3.GENDER_TYPES:
        not_listed.append(value)
print(not_listed)

[nan, 'UNKNOWN']


In [33]:
not_listed = []
for value in df['MARITAL_STATUS'].str.upper().unique():
    if value not in constants_uc3.MARITAL_STATUSES:
        not_listed.append(value)
print(not_listed)

[nan, 'UNKNWN']


In [34]:
not_listed = []
for value in df['RELIGION'].str.upper().unique():
    if value not in constants_uc3.RELIGION_TYPES:
        not_listed.append(value)
print(not_listed)

[nan, 'NONE', '9']


In [81]:
not_listed = []
for value in df['NATIONALITY'].str.upper().unique():
    consts = [const.upper() for const in constants_uc3.NATIONALITIES]
    if value not in consts:
        not_listed.append(value)
print(not_listed)

['SINGAPORE', 'JAPAN', 'AUSTRALIA', 'INDONESIA', 'UNITED KINGDOM', 'SWITZERLAND', 'EGYPT', 'SOUTH AFRICA', 'PHILIPPINES', 'MALAYSIA', 'SPAIN', 'GERMANY', 'INDIA', 'CHINA', 'RUSSIAN FED.', 'BRAZIL', 'AUSTRIA', 'CANADA', 'VIETNAM', 'MYANMAR', 'USA', nan, 'BRUNEI DARUSS.', 'BANGLADESH', 'ARGENTINA', 'VENEZUELA', 'FRANCE', 'TAIWAN', 'GEORGIA', 'THAILAND', 'IRAN', 'LAOS', 'UTD.ARAB EMIR.', 'CAMBODIA', 'NETHERLANDS', 'MOROCCO', 'SRI LANKA', 'SOUTH KOREA', 'PAKISTAN', 'DENMARK', 'ITALY', 'IRELAND', 'ISRAEL', 'SEYCHELLES', 'KAZAKHSTAN', 'UKRAINE', 'UZBEKISTAN', 'CZECH REPUBLIC', 'SWEDEN', 'MEXICO', 'UNKNOWN', 'ST KITTS&NEVIS', 'NEPAL', 'MAURITIUS', 'PORTUGAL', 'BELGIUM', 'ROMANIA', 'MACAU', 'BULGARIA', 'MONGOLIA', 'TURKEY', 'GUAM', 'MALDIVES', 'ALGERIA', 'NORTH KOREA', 'LUCIAN', 'NICARAGUAN', 'MISSING', 'SERB/MONT', 'BURKINABE', 'PALESTINIAN']


In [36]:
not_listed = []
for value in df['RESID_CTY'].str.upper().unique():
    consts = [const.upper() for const in constants_uc3.COUNTRY_CODES]
    if value not in consts:
        not_listed.append(value)
print(not_listed)

[nan, 'UNKNOWN']


In [106]:
not_listed = []
for value in df['OCCUPATION'].str.upper().unique():
    consts = [const.upper() for const in constants_uc3.OCCUPATIONS]
    if value not in consts:
        not_listed.append(value)
print(not_listed)

[nan, 'NIL', '-', 'NA', 'OTHERS', 'NONE', 'LETRUONGTHAONHI@GMAIL.COM', 'SANTUL.CHANDRA@SC.COM', 'ROYSTON.TAN@TADANO.COM', 'MALAYSIAN', 'DENNIS.SIM@SC.COM', 'SHAHRIZAN.MANSOR@SC.COM', 'RONALD.BUDER@GMAIL.COM']


In [109]:
not_listed = []
for value in df['RESID_GEOAREA'].str.upper().unique():
    consts = [const.upper() for const in constants_uc3.RESID_LOCATIONS]
    if value not in consts:
        not_listed.append(value)
print(not_listed)

[nan]


In [110]:
df['NONRESID_FLAG'].str.upper().unique()

array(['N', 'Y', nan], dtype=object)

In [114]:
not_listed = []
for value in df['IDENT_TYPE'].str.upper().unique():
    consts = [const.upper() for const in constants_uc3.ID_TYPES]
    if value not in consts:
        not_listed.append(value)
print(not_listed)

['OTHERS', nan]


In [117]:
not_listed = []
for value in df['CONT_RELATION'].str.upper().unique():
    consts = [const.upper() for const in constants_uc3.RELATIONS]
    if value not in consts:
        not_listed.append(value)
print(not_listed)

[nan]


In [42]:
print(df.select_dtypes(exclude=['object']).nunique())
print(len(df.select_dtypes(exclude=['object']).columns))

ACTUAL_CASE_NUMBER              62517
ACTUAL_PATIENT_NUMBER           54952
ACTUAL_PRIMARY_DIAGNOSIS_SID     3778
ACTUAL_ADMISSION_DTE              442
ACTUAL_LOS                         66
ACTUAL_ICU_HDU_LOS                 14
ADM_DATE                          442
CASE_NO                         49381
ETBS_LOS                           22
PATIENT_TYPE                        0
PATIENT_NUMBER                  54842
DOB                             23093
RESID_POSTALCODE                19124
CONT_POSTAL                     18720
TOTAL_HOSP                      58326
dtype: int64
15


In [43]:
print(df.select_dtypes(exclude=[np.number, np.object]).nunique())

ACTUAL_ADMISSION_DTE      442
ADM_DATE                  442
DOB                     23093
dtype: int64


In [44]:
print('ACTUAL_ADMISSION_DTE vs ADM_DATE: ',
      df.groupby(by=['ACTUAL_ADMISSION_DTE'])['ADM_DATE'].nunique().max())

ACTUAL_ADMISSION_DTE vs ADM_DATE:  1


In [134]:
print(df.select_dtypes(include=[np.number]).nunique())
print(len(df.select_dtypes(include=[np.number]).columns))
print(df.select_dtypes(include=[np.number]).info())

ACTUAL_CASE_NUMBER              62517
ACTUAL_PATIENT_NUMBER           54952
ACTUAL_PRIMARY_DIAGNOSIS_SID     3778
ACTUAL_LOS                         66
ACTUAL_ICU_HDU_LOS                 14
CASE_NO                         49381
ETBS_LOS                           22
PATIENT_TYPE                        0
PATIENT_NUMBER                  54842
RESID_POSTALCODE                19124
CONT_POSTAL                     18720
TOTAL_HOSP                      58326
dtype: int64
12
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 62517 entries, 0 to 62516
Data columns (total 12 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   ACTUAL_CASE_NUMBER            62517 non-null  int64  
 1   ACTUAL_PATIENT_NUMBER         62517 non-null  int64  
 2   ACTUAL_PRIMARY_DIAGNOSIS_SID  62517 non-null  int64  
 3   ACTUAL_LOS                    62517 non-null  int64  
 4   ACTUAL_ICU_HDU_LOS            49 non-null     float64
 5   C

In [46]:
print(df[df.duplicated(subset=['ACTUAL_CASE_NUMBER'], keep=False)])

Empty DataFrame
Columns: [ACTUAL_CASE_NUMBER, ACTUAL_TREATMENT_CATEGORY, ACTUAL_PATIENT_NUMBER, ACTUAL_PRIMARY_DIAGNOSIS_SID, ACTUAL_CASE_INSTITUTION, ACTUAL_ADMISSION_DTE, ACTUAL_LOS, ACTUAL_ICU_HDU_LOS, ACTUAL_SURGICAL_CODE_1, ACTUAL_SURGICAL_CODE_2, ACTUAL_SURGICAL_CODE_3, ACTUAL_DIAGNOSIS_CODE, ADM_DATE, INST, CASE_NO, ETBS_LOS, ETBS_ICU_HDU_LOS, ETBS_MOVE_TYPE, ETBS_TOSP_1, ETBS_TOSP_2, ETBS_TOSP_3, ETBS_ICD10_1, ETBS_ICD10_2, ETBS_ICD10_3, CASE_TYPE, PATIENT_TYPE, ADMISSION_TYPE, TREATMENT_CATEGORY, REFERRAL_TYPE, DEPT_OU, ADMITTING_SMC_NUMBER, ATTENDING_SMC_NUMBER, REFERRAL_SMC_NUMBER, ADM_CLASS_DISC, PATIENT_NUMBER, GENDER, DOB, MARITAL_STATUS, RELIGION, NATIONALITY, RESID_CTY, RESID_POSTALCODE, OCCUPATION, RESID_GEOAREA, NONRESID_FLAG, IDENT_TYPE, CONT_POSTAL, CONT_RELATION, TOTAL_HOSP]
Index: []

[0 rows x 49 columns]


In [47]:
print(df['PATIENT_TYPE'].unique())

[nan]


In [48]:
print('ACTUAL_CASE_NUMBER vs CASE_NO: ',
      df.groupby(by=['ACTUAL_CASE_NUMBER'])['CASE_NO'].nunique().max())
print(df.groupby(by=['ACTUAL_CASE_NUMBER'])['CASE_NO'].head())

ACTUAL_CASE_NUMBER vs CASE_NO:  1
0                 NaN
1                 NaN
2                 NaN
3                 NaN
4                 NaN
             ...     
62512    1.020009e+09
62513    4.020010e+09
62514    4.020010e+09
62515    1.020009e+09
62516    4.020005e+09
Name: CASE_NO, Length: 62517, dtype: float64


In [49]:
print('ACTUAL_PATIENT_NUMBER vs PATIENT_NUMBER: ',
      df.groupby(by=['ACTUAL_PATIENT_NUMBER'])['PATIENT_NUMBER'].nunique().max())
print(df.groupby(by=['ACTUAL_PATIENT_NUMBER'])['PATIENT_NUMBER'].head())

ACTUAL_PATIENT_NUMBER vs PATIENT_NUMBER:  1
0        4471730.0
1        5148520.0
2        6112323.0
3        6112322.0
4        6098582.0
           ...    
62512    3679873.0
62513    6261014.0
62514    6120029.0
62515    5485720.0
62516    6256103.0
Name: PATIENT_NUMBER, Length: 62310, dtype: float64


In [50]:
print('ACTUAL_CASE_NUMBER vs ACTUAL_PATIENT_NUMBER: ',
      df.groupby(by=['ACTUAL_CASE_NUMBER'])['ACTUAL_PATIENT_NUMBER'].nunique().max())
print(df.groupby(by=['ACTUAL_CASE_NUMBER'])['ACTUAL_PATIENT_NUMBER'].head())

ACTUAL_CASE_NUMBER vs ACTUAL_PATIENT_NUMBER:  1
0        4471730
1        5148520
2        6112323
3        6112322
4        6098582
          ...   
62512    3679873
62513    6261014
62514    6120029
62515    5485720
62516    6256103
Name: ACTUAL_PATIENT_NUMBER, Length: 62517, dtype: int64


In [51]:
print('ACTUAL_CASE_NUMBER vs PATIENT_NUMBER: ',
      df.groupby(by=['ACTUAL_CASE_NUMBER'])['PATIENT_NUMBER'].nunique().max())

ACTUAL_CASE_NUMBER vs PATIENT_NUMBER:  1


In [52]:
print('CASE_NO vs ACTUAL_PATIENT_NUMBER: ',
      df.groupby(by=['CASE_NO'])['ACTUAL_PATIENT_NUMBER'].nunique().max())

CASE_NO vs ACTUAL_PATIENT_NUMBER:  1


In [53]:
print('CASE_NO vs PATIENT_NUMBER: ',
      df.groupby(by=['CASE_NO'])['PATIENT_NUMBER'].nunique().max())

CASE_NO vs PATIENT_NUMBER:  1


In [147]:
print('ACTUAL_CASE_NUMBER vs ACTUAL_PRIMARY_DIAGNOSIS_SID: ',
      df.groupby(by=['ACTUAL_CASE_NUMBER'])['ACTUAL_PRIMARY_DIAGNOSIS_SID'].nunique().max())

ACTUAL_CASE_NUMBER vs ACTUAL_PRIMARY_DIAGNOSIS_SID:  1


In [131]:
print('ACTUAL_LOS vs ETBS_LOS: ',
      df.groupby(by=['ACTUAL_LOS'])['ETBS_LOS'].nunique().max())
print(df['ACTUAL_LOS'].unique())
print(df['ETBS_LOS'].unique())

ACTUAL_LOS vs ETBS_LOS:  11
[  0  10   1   8   3   6   4  11   9   2   5   7  16  18  14  35  12  23
  29  13  17  32  28  40  26  20  45  31  61  15  21  48  36  54  63  22
  51  19  27  24  34  30  50  25  37  38  47  52  72  43  70  68  56  55
 100  46  33  44  39  67  41 130  98  76  64  79]
[  1.  nan   2.   3.   5.   7.   4.   6.  10.  14.  22.  30.   8.  20.
  11.  28.   9.  12. 111.  21.  42.  49.  32.]


In [138]:
print(df['ACTUAL_PRIMARY_DIAGNOSIS_SID'].unique())
print(df['ACTUAL_PRIMARY_DIAGNOSIS_SID'].isna().sum())

[ 8976 13220 26921 ... 20130  8054 24384]
0


In [144]:
print(df['ACTUAL_ICU_HDU_LOS'].value_counts())
print(df['ACTUAL_ICU_HDU_LOS'].isna().sum())

2.0     13
4.0      7
3.0      6
7.0      5
6.0      4
5.0      4
8.0      3
15.0     1
13.0     1
12.0     1
14.0     1
18.0     1
9.0      1
16.0     1
Name: ACTUAL_ICU_HDU_LOS, dtype: int64
62468


In [140]:
print(df['CASE_NO'].unique())
print(df['CASE_NO'].isna().sum())

[           nan 4.01807619e+09 1.01808677e+09 ... 4.02000976e+09
 1.02000882e+09 4.02000532e+09]
13117


In [143]:
print(df['ETBS_LOS'].value_counts())
print(df['ETBS_LOS'].isna().sum())

1.0      39307
2.0      13449
3.0       6279
5.0        767
4.0        720
7.0        290
6.0         87
10.0        51
14.0        20
8.0          5
30.0         3
21.0         2
9.0          2
28.0         2
11.0         2
20.0         2
111.0        1
12.0         1
49.0         1
32.0         1
42.0         1
22.0         1
Name: ETBS_LOS, dtype: int64
1523


In [145]:
print(df['PATIENT_NUMBER'].unique())
print(df['PATIENT_NUMBER'].isna().sum())

[4471730. 5148520. 6112323. ... 6120029. 5485720. 6256103.]
122


In [146]:
print(df['RESID_POSTALCODE'].unique())
print(df['RESID_POSTALCODE'].isna().sum())

[509730. 679695. 239899. ... 278093. 109345. 268485.]
11832


In [137]:
print(df['CONT_POSTAL'].unique())
print(df['CONT_POSTAL'].isna().sum())

[509730. 688536. 239899. ... 238334. 669487. 268485.]
14244


In [54]:
index_col = 'ACTUAL_CASE_NUMBER'
col_drop = [
    'INST', # represented by 'ACTUAL_CASE_INSTITUTION'
    'ACTUAL_PATIENT_NUMBER','CASE_NO','PATIENT_NUMBER','ACTUAL_PRIMARY_DIAGNOSIS_SID', # represented by 'ACTUAL_CASE_NUMBER'
    'CASE_TYPE','PATIENT_TYPE', # single value features
    'ADM_DATE','ACTUAL_ADMISSION_DTE','DOB', # aggregate to admission age
    'RESID_POSTALCODE','CONT_POSTAL', # drop postal codes for now
    ]